server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  cloud:
    alibaba:
      seata:
        #与file.conf中service.vgroupMapping一致，不配置需要修改file.conf中的值为${application.name}-fescar-service-group
        tx-service-group: my_test_tx_group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: error
    io.seata: info


